### ISSUE TITLE
refactor 3-appfactory

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/terraform-google-enterprise-application#111]

**Comment by yliaog** [comment]
>> remove unused TF code (only cymbal-bank/frontend was utilized by code, which has been renamed cymbal-bank)

i think the intent is for each app having its own appfactory, each app's cicd pipeline is created in their respective appfactory admin project. similar to https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/78, the 5 other apps also have their integration tests.

**Comment by apeabody** [comment]
> > > remove unused TF code (only cymbal-bank/frontend was utilized by code, which has been renamed cymbal-bank)
> 
> i think the intent is for each app having its own appfactory, each app's cicd pipeline is created in their respective appfactory admin project. similar to #78, the 5 other apps also have their integration tests.

Thanks @yliaog!

Looking through the [code](https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/blob/main/test/integration/appfactory/appfactory_test.go#L47) and CI logs, it appears the `frontend` appfactory is currently used for all apps in stage 5 - hence my rename to `cymbal-bank`.  However if the intention was to use a dedicated appfactory for each of those (`frontend`, `accounts-contacts`, etc), I can certainly make that change in https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/112 by updating appfactory_test.go to point to `apps/cymbal-bank` instead of `apps/cymbal-bank/frontend` - probably need some downstream tweaks as well.

I'll mock it up prior to our next call. :)
