### ISSUE TITLE
nonproduction vs non-production

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/terraform-google-enterprise-application#178]
We currently have a mix of `nonproduction ` and `non-production` (primarily the latter) both in this repo and https://cloud.google.com/architecture/enterprise-application-blueprint/architecture.

**Comment by gtsorbo** [comment]
We should move entirely to `nonproduction` as is the case in EFB: https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/2-environments/envs

**Comment by apeabody** [comment]
Let's address after https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/pull/154 is merged as it will simplify the change.
